//! Bakes the web app into the binary.
//!
//! The wasm in `pkg/` is optional: when it has not been built the binary still
//! ships a complete, working app, because `wasm-bridge.js` falls back to the
//! JavaScript implementations in `app.js`.

use std::path::{Path, PathBuf};

/// (URL path, source file, MIME type, required)
const ASSETS: &[(&str, &str, &str, bool)] = &[
    ("/index.html", "index.html", "text/html; charset=utf-8", true),
    ("/style.css", "style.css", "text/css; charset=utf-8", true),
    ("/app.js", "app.js", "text/javascript; charset=utf-8", true),
    (
        "/wasm-bridge.js",
        "wasm-bridge.js",
        "text/javascript; charset=utf-8",
        true,
    ),
    (
        "/pkg/mapcheck_wasm.js",
        "pkg/mapcheck_wasm.js",
        "text/javascript; charset=utf-8",
        false,
    ),
    (
        // The browser refuses to stream-instantiate this as anything but
        // application/wasm.
        "/pkg/mapcheck_wasm_bg.wasm",
        "pkg/mapcheck_wasm_bg.wasm",
        "application/wasm",
        false,
    ),
];

fn main() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root");

    let mut entries = String::new();
    let mut embedded_wasm = false;

    for (url, file, mime, required) in ASSETS {
        let path: &Path = &root.join(file);
        println!("cargo:rerun-if-changed={}", path.display());

        if !path.exists() {
            if *required {
                panic!("missing asset: {}", path.display());
            }
            continue;
        }
        if file.starts_with("pkg/") {
            embedded_wasm = true;
        }
        entries.push_str(&format!(
            "    Asset {{ path: {:?}, mime: {:?}, bytes: include_bytes!({:?}) }},\n",
            url,
            mime,
            path.display().to_string()
        ));
    }

    let generated = format!(
        "// Generated by build.rs. Do not edit.\n\
         pub struct Asset {{\n\
         \x20   pub path: &'static str,\n\
         \x20   pub mime: &'static str,\n\
         \x20   pub bytes: &'static [u8],\n\
         }}\n\n\
         /// Whether the Rust/WASM core was available at build time.\n\
         pub const EMBEDDED_WASM: bool = {embedded_wasm};\n\n\
         pub static ASSETS: &[Asset] = &[\n{entries}];\n"
    );

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("assets.rs");
    std::fs::write(&out, generated).expect("write assets.rs");

    // pkg/ appearing or disappearing changes what gets embedded.
    println!("cargo:rerun-if-changed={}", root.join("pkg").display());
}
